FROM node:18-alpine AS build

WORKDIR /app

COPY dashboard-ui/package.json dashboard-ui/package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY dashboard-ui ./dashboard-ui
WORKDIR /app/dashboard-ui
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dashboard-ui/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
